### ISSUE TITLE
"Subject" query issues

### ISSUE THREAD

**Issue by Akillus** [codarchlab/ariadne-portal#167]
Inconsistencies when a value from the "Derived Subjects" facet is selected. E.g.:
1. By selecting "houses", we get 86.755 records. By clicking on one of them and then again on the "houses"  subject or on the related "buildings (structure)" subject from the resource page, nothing appears and the new query provides empty results.
2. From the same page, by clicking on the "i" besides the "houses" AAT subject, the "Search connected resource" on the top-right corner of the AAT subject page says "47.375", a different number of available resources indeed.

**Comment by eafiontzi** [comment]
1. This is caused because when you were clicking on the term it was looking for the term "houses" in the native subject instead of the derived, it will be fixed.
2. This inconsistency appears because when searching for connected resources we also filter only results that have coordinates. That will be fixed as well. Though if you click on the link of the connected resources you get the same number of records as before in the search results (86.755)

Thanks for the info!
