### ISSUE TITLE
Better looking url with temporal filters active

### ISSUE THREAD

**Issue by jfihn** [codarchlab/ariadne-portal#74]
e.g. http://ariadne-portal.dcu.gr/search?q=&temporal=%0A+++++++++++++++%0A++++++++++++++++++Medieval%0A+++++++++++++++%0A++++++++++++

**Comment by eafiontzi** [comment]
I think it is the same issue with a bug that was fixed because the temporal periodNames contain many /n, /t etc (for example  "periodName": "\n               \n                  Modern\n               \n            "). Do you think we could replace those in the aggregation itself or we shoul eliminate those characters before it is published in ES?

**Comment by borsna** [comment]
It would be best to trim leading/tailing \n and " " before inserting into ES.
Otherwhise the filter: http://ariadne-portal.dcu.gr/search?temporal=Medieval wont work (the filter uses the excat matcing).
So: http://ariadne-portal.dcu.gr/search?temporal=%0A+++++++++++++++%0A++++++++++++++++++Medieval%0A+++++++++++++++%0A++++++++++++ works while http://ariadne-portal.dcu.gr/search?temporal=Medieval wont

**Comment by eafiontzi** [comment]
Yeap, I too believe they must be trimmed before inserting into ES.

I also believe it would be better if the filters were not using exact matching (for instance if someone is searching Bronze it would not get any results because the exact matching is Bronze Age).
We could use something like a wildcard which I have used in other projects https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-wildcard-query.html

**Comment by eafiontzi** [comment]
trimmed before inserting in ES
