### ISSUE TITLE
Markers on map show locations names instead of resource title

### ISSUE THREAD

**Issue by jfihn** [codarchlab/ariadne-portal#81]
Comment from user group.

Use case:
Point-details – If the user clicks on one of the indicators then a popup displays a summary of the metadata (equal to list-view) and a link to the preview-page of the entry.

The markers show resources and not locations, which makes it more reasonable to show resource title and perhaps some more metadata. Link should possibly go to the resource and not to a new search.

**Comment by scuy** [comment]
The markers intentionally represent places and not resources since sometimes there is more than one resource connected to a place (e.g. http://ariadne-portal.dcu.gr/search?q=spatial.location.lon:%220.889007%22%20AND%20spatial.location.lat:%2251.13811%22).

We could however try to cover both cases and directly link to the resource if there is only one.

**Comment by scuy** [comment]
Another possible solution would be to implement clustering of markers representing single resource. Several markers at the same position on the map could be visualized as a stack of markers that can be extended by clicking on it (similar to Google Earth).
