### ISSUE TITLE
Icon for accessing the resource on the web from search result

### ISSUE THREAD

**Issue by scuy** [codarchlab/ariadne-portal#90]
As depicted in the mockups (page 4) ...

**Comment by eafiontzi** [comment]
Do you think it is better to have the image this way:
![image](https://cloud.githubusercontent.com/assets/14819444/12777633/c7c2ca42-ca66-11e5-9e86-1f280480b254.png)

or like that:
![image](https://cloud.githubusercontent.com/assets/14819444/12777605/9c122726-ca66-11e5-8971-d54b8a4806d0.png)

I think like it better in the first scenario because the connection is more clear, but the thing is that there is a call on the whole div to go to the resource page on click, so when clicking on the icon it opens a new window with the landing page, but the search results page gets redirected to the specific resource, which does not happen in the second way.

Let me know what you think

**Comment by borsna** [comment]
I also think the first one is the clearest one. 
There should also be a tooltip telling the user this is an external landing page.

**Comment by eafiontzi** [comment]
Yeap, but should we leave the functionality that redirects the search results page to the specific resource or remove it from the whole div and leave it only in the title? Another option is to have the second view and expand the on hover color.

A tooltip should be there, I believe it is already noted in the comments of the tooltip issue ;)

**Comment by scuy** [comment]
I would also prefer the first solution. Maybe you can prevent the outer onClick event from firing with [event.stopPropagation()](https://stackoverflow.com/questions/387736/how-to-stop-event-propagation-with-inline-onclick-attribute)?

**Comment by eafiontzi** [comment]
Great tip! Worked well I think :+1: 65214b9787844fe26a1ba1f1486e2a98f046c404
